### ISSUE TITLE
implement add todo functionality

### ISSUE THREAD

**Issue by Yokosumi** [Yokosumi/sc010-todo-app#1]
- [x]  First make sure you can add a new todo in the backend
- [x] Secondly, make sure you can add a new todo by sending a `POST` Request to the Backend with the payload
- [ ] implement clear when send

 ---
## The POST Todo Function looks like:

![Image](https://github.com/Yokosumi/sc010-todo-app/assets/95232477/c35e389f-8f93-45ad-91a2-d9a356acc2a4)
